modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="magica"
version="1.0.0"
displayName="Magica"
credits="Kvas0k, Kascun, Nikjust"
displayURL="MCREATOR: https://mcreator.net"
logoFile="logo.png"
authors="DIVINE CODERS"
description='''
Adds Techno-magic by Global Magica and red & blue magica
'''

[[dependencies.magica]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



[[dependencies.magica]]
    modId="just_enough_items"
    mandatory=false
    ordering="NONE"
    side="BOTH"

