modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="magica"
version="1.0.0"
displayName="Magica"
credits="Created By NikJust(or Õ» , nikki, nikjust08)"
displayURL="MCREATOR: https://mcreator.net"
authors="NikJust"
description='''
Adds Techno-magic by Global Magica and red & blue magica
'''

[[dependencies.magica]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"




